-- Historical migration placeholder restored for databases that already applied
-- 20260504051439_add_signup_fields before this backend zip was assembled.
-- The original SQL was not present in the current or old local project copies.
-- Do not add schema changes here; current forward migrations preserve data.
