-- Historical migration placeholder restored for databases that already applied
-- 20260519001000_make_refresh_token_hash_nullable before this backend zip was assembled.
-- The original SQL was not present in the current or old local project copies.
-- Do not add schema changes here; current forward migrations preserve data.
